---
title: "Practical_Machine_Learning_Project"
author: "Lukas Mao"
date: "10/04/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Import data

```{r}
pml_training <- read.csv("C:/Users/lukas/Downloads/pml-training.csv",header = T)
pml_testing <- read.csv("C:/Users/lukas/Downloads/pml-testing.csv",header = T)

```

2. Data Cleaning

```{r}
pml_training <- read.csv("C:/Users/lukas/Downloads/pml-training.csv",header = T,na.strings=c("NA",""))
pml_testing <- read.csv("C:/Users/lukas/Downloads/pml-testing.csv",header = T,na.strings=c("NA",""))
pml_training <- pml_training[,colSums(is.na(pml_training)) == 0]
pml_testing <- pml_testing[,colSums(is.na(pml_testing)) == 0]
```

In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. Thus we delete the unrelated variables.

```{r}
pml_training <- pml_training[,-c(1:7)]
pml_testing <- pml_testing[,-c(1:7)]
```

3. Predicting
```{r}
library(caret)

set.seed(1001)
inTrain <- createDataPartition(y=pml_training$classe, p=3/4, list=FALSE)
pml_training_train <- pml_training[inTrain,] 
pml_training_test <- pml_training[-inTrain,]
```

To see the structure of different classes.
```{r}
histogram(pml_training_train$classe,pml_training_train,xlab = "Classes",
        ylab="Percentage",main="Frequency of each type in Training data")
```

Machine Learning Method 1: rpart

```{r}
library(rpart)
modFit <- rpart(classe ~ .,data=pml_training_train,method="class")
train_pred <- predict(modFit,pml_training_test,type = "class")
confusionMatrix(train_pred,pml_training_test$classe)
```

Machine Learning Method 2: random forest
```{r}
library(randomForest)
modFit <- randomForest(classe ~., data=pml_training_train, method="class")
train_pred <- predict(modFit,newdata = pml_training_test,type = "class")
confusionMatrix(train_pred,pml_training_test$classe)
```

Finally, we predict the 20 predicting tests.
```{r}
test_pred <- predict(modFit,newdata = pml_testing)
test_pred
```